"""Add user_activity_logs table

Revision ID: f7afd3893dd2
Revises: ecd98f26671f
Create Date: 2025-12-29 20:17:30.107009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7afd3893dd2'
down_revision: Union[str, None] = 'ecd98f26671f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
